[mypy]

[mypy-Carbon.*]
ignore_missing_imports = True

[mypy-creole.*]
ignore_missing_imports = True

[mypy-py2exe.*]
ignore_missing_imports = True

[mypy-pyopl.*]
ignore_missing_imports = True

[mypy-wx.*]
ignore_missing_imports = True

[mypy-wx.lib.newevent.*]
ignore_missing_imports = True
