[package]
name = "dro-ui"
description = "The egui application as a library, parameterized by platform-service traits. Native and wasm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]

[lints]
workspace = true
