name: Build and package app

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Formatting
        run: |
          python -m black --check ./src

      - name: Type checking
        run: |
          python -m mypy ./src

      - name: Run setup
        run: |
          cd src
          python ./setup.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drotrimmer-bin-and-src
          path: dist/
